# Generated by Django 5.1.3 on 2024-11-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
