# Generated by Django 5.1.3 on 2024-12-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_category_budget_limit_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
